name: Bug Fix Pull Request
description: Propose a bug fix
title: "[Bug Fix]: "
labels: [bug, fix]
body:
  - type: input
    id: issue
    attributes:
      label: Related Issue
      description: Link to the issue that is being fixed.
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the bug and how this fixes it.
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have tested the fix.
          required: true
        - label: I have updated the documentation.
          required: false
