name: Code Refactoring
description: Suggest a code refactoring for the project
title: "[Refactoring]: "
labels: ["refactoring"]
assignees: ["username1", "username2"]
body:
  - type: markdown
    attributes:
      value: |
        ## Code Refactoring

        Please provide as much detail as you can about the code refactoring suggestion.
  - type: textarea
    id: refactoring-description
    attributes:
      label: Please describe the part of the codebase that needs refactoring.
      description: Provide a clear and concise description of what part of the codebase needs refactoring.
    validations:
      required: true
  - type: textarea
    id: refactoring-reason
    attributes:
      label: Why does this need to be refactored?
      description: Describe why this part of the codebase needs refactoring.
    validations:
      required: true
  - type: textarea
    id: suggested-refactoring
    attributes:
      label: Do you have a suggested way to refactor this?
      description: If you have ideas on how to refactor this, please share!
    validations:
      required: false
