name: Performance Issue
description: Report a performance issue in the project
title: "[Performance]: "
labels: ["performance"]
assignees: ["username1", "username2"]
body:
  - type: markdown
    attributes:
      value: |
        ## Performance Issue

        Please provide as much detail as you can about the performance issue.
  - type: textarea
    id: performance-description
    attributes:
      label: Please describe the performance issue.
      description: Provide a clear and concise description of what the performance issue is.
    validations:
      required: true
  - type: textarea
    id: performance-reproduction
    attributes:
      label: Steps to reproduce the performance issue.
      description: Provide a list of steps to reproduce the performance issue here.
    validations:
      required: true
  - type: textarea
    id: performance-impact
    attributes:
      label: What is the impact of this performance issue?
      description: Describe how this performance issue affects the user experience or system performance.
    validations:
      required: true
  - type: textarea
    id: suggested-fix
    attributes:
      label: Do you have a suggested fix?
      description: If you have ideas on how to fix this, please share!
    validations:
      required: false
