name: Security Vulnerability
description: Report a security vulnerability in the project
title: "[Security]: "
labels: ["security"]
assignees: ["username1", "username2"]
body:
  - type: markdown
    attributes:
      value: |
        ## Security Vulnerability

        Please provide as much detail as you can about the security vulnerability.
  - type: textarea
    id: vulnerability-description
    attributes:
      label: Please describe the vulnerability.
      description: Provide a clear and concise description of what the vulnerability is.
    validations:
      required: true
  - type: textarea
    id: vulnerability-reproduction
    attributes:
      label: Steps to reproduce the vulnerability.
      description: Provide a list of steps to reproduce the vulnerability here.
    validations:
      required: true
  - type: textarea
    id: potential-impact
    attributes:
      label: What is the potential impact of this vulnerability?
      description: Describe what damage an attacker could potentially do if this vulnerability is exploited.
    validations:
      required: true
  - type: textarea
    id: suggested-fix
    attributes:
      label: Do you have a suggested fix?
      description: If you have ideas on how to fix this, please share!
    validations:
      required: false
