name: Community Proposal
description: Propose a community event or initiative for the project
title: "[Community]: "
labels: ["community", "proposal"]
assignees: ["username1", "username2"]
body:
  - type: markdown
    attributes:
      value: |
        ## Community Proposal

        Please provide as much detail as you can about the proposed community event or initiative.
  - type: textarea
    id: proposal-description
    attributes:
      label: Please describe the community event or initiative.
      description: Provide a clear and concise description of the community event or initiative you're proposing.
    validations:
      required: true
  - type: textarea
    id: proposal-reason
    attributes:
      label: Why are you proposing this event or initiative?
      description: Describe the reasons for proposing this community event or initiative.
    validations:
      required: true
  - type: textarea
    id: proposal-benefit
    attributes:
      label: How would this benefit the project's community?
      description: Explain how this event or initiative would benefit the project's community.
    validations:
      required: true