name: Data Issue
description: Report a data issue in the project
title: "[Data]: "
labels: ["data"]
assignees: ["username1", "username2"]
body:
  - type: markdown
    attributes:
      value: |
        ## Data Issue

        Please provide as much detail as you can about the data issue.
  - type: textarea
    id: data-issue-description
    attributes:
      label: Please describe the data issue.
      description: Provide a clear and concise description of what the data issue is.
    validations:
      required: true
  - type: textarea
    id: data-issue-impact
    attributes:
      label: How does this issue affect the project?
      description: Describe how this data issue affects the project.
    validations:
      required: true
  - type: textarea
    id: suggested-fix
    attributes:
      label: Do you have a suggested fix?
      description: If you have ideas on how to fix this, please share!
    validations:
      required: false
