name: Technical Debt
description: Report a technical debt item in the project
title: "[Technical Debt]: "
labels: ["technical debt"]
assignees: ["username1", "username2"]
body:
  - type: markdown
    attributes:
      value: |
        ## Technical Debt

        Please provide as much detail as you can about the technical debt item.
  - type: textarea
    id: debt-description
    attributes:
      label: Please describe the technical debt item.
      description: Provide a clear and concise description of what the technical debt item is.
    validations:
      required: true
  - type: textarea
    id: debt-impact
    attributes:
      label: Why is this a problem?
      description: Describe why this technical debt item is a problem for the project.
    validations:
      required: true
  - type: textarea
    id: suggested-fix
    attributes:
      label: Do you have a suggested fix?
      description: If you have ideas on how to fix this, please share!
    validations:
      required: false
